export const ADD_RECORD_REQUEST = "ADD_RECORD_REQUEST";
export const ADD_RECORD_SUCCESS = "ADD_RECORD_SUCCESS";
export const ADD_RECORD_FAIL = "ADD_RECORD_FAIL";

export const UPDATE_RECORD_REQUEST = "UPDATE_RECORD_REQUEST";
export const UPDATE_RECORD_SUCCESS = "UPDATE_RECORD_SUCCESS";
export const UPDATE_RECORD_FAIL = "UPDATE_RECORD_FAIL";

export const DELETE_RECORD_REQUEST = "DELETE_RECORD_REQUEST";
export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";
export const DELETE_RECORD_FAIL = "DELETE_RECORD_FAIL";
